export enum ApplicationRole {
  ADMIN = 2,
  BRANCH_MANAGER = 4,
  DELIVERYMAN = 5,
  SUBERVISOR = 6,
  Call_Center = 7,
  RENTER_OFFICER = 8,
  AREA_MANAGER = 9,
  // User = 10 ,
  DISPATCHER = 10,
  OPERATOR = 11,
  MARKETING_MANAGER = 12,
  DELIVERY_PROVIDER = 13,
  DEVELOPER = 14,
  STORE_MANAGER = 15,
  VENDOR_MANAGER = 18,





}
